### PR TITLE
updated + simplified dropdown menu

### PR DESCRIPTION
**Pull request by craragon77**
simplified the dropdown menu's timezones. I removed the UTC+GMT and left only the local timezome. Made new branch off of the ofi-release-1 branch instead of the development for these changes.

### CODE REVIEW

**Comment by craragon77** [comment]
@reshadbinharun hey dude, i just made the tweaks you requested from yesterday on a new branch (based on the ofi-release-1.0 instead of the development branch). Let me know your thoughts :)

**Comment by reshadbinharun** [comment]
> @reshadbinharun hey dude, i just made the tweaks you requested from yesterday on a new branch (based on the ofi-release-1.0 instead of the development branch). Let me know your thoughts :)

thanks for recreating this PR! Let's actually keep all the timezones and only get rid of GMT offsets in parentheses (since we're expecting to work across a few different regions)

**Comment by craragon77** [comment]
just added back the o.g. timezones (without the UTC/GMT), but let me know if there are other changes I can make

**Review by reshadbinharun — APPROVED** [review]
Looks good!

**Pull request merged**
